import { correctness as effectTsgoCorrectness } from "@effect/tsgo/oxlint-presets";
import "vite-plus/test/config";
import { defineConfig } from "vite-plus";

export default defineConfig({
  test: {
    environment: "node",
    hookTimeout: 60_000,
    testTimeout: 60_000,
  },
  staged: {
    "*": "vp check --fix",
  },
  fmt: {
    ignorePatterns: [
      ".reference",
      ".repos/**",
      ".plans",
      "dist",
      "dist-electron",
      "node_modules",
      "pnpm-lock.yaml",
      "*.tsbuildinfo",
      "**/routeTree.gen.ts",
      "apps/mobile/android/**",
      "apps/mobile/ios/**",
      "apps/web/public/mockServiceWorker.js",
      "apps/web/src/lib/vendor/qrcodegen.ts",
      "apps/mobile/uniwind-types.d.ts",
      "*.icon/**",
    ],
    sortPackageJson: {},
    overrides: [
      {
        files: [".devcontainer/devcontainer.json"],
        options: {
          trailingComma: "none",
        },
      },
    ],
  },
  lint: {
    ignorePatterns: [
      ".repos",
      ".repos/**",
      "dist",
      "dist-electron",
      "node_modules",
      "pnpm-lock.yaml",
      "*.tsbuildinfo",
      "**/routeTree.gen.ts",
      "apps/mobile/android/**",
      "apps/mobile/ios/**",
      "apps/mobile/uniwind-types.d.ts",
    ],
    plugins: [...effectTsgoCorrectness.plugins!, "eslint", "oxc", "react", "unicorn", "typescript"],
    jsPlugins: ["./oxlint-plugin-salchi/index.ts"],
    categories: {
      correctness: "warn",
      suspicious: "warn",
      perf: "warn",
    },
    rules: {
      "unicorn/no-array-sort": "off",
      "unicorn/consistent-function-scoping": "off",
      "oxc/no-map-spread": "off",
      "react-in-jsx-scope": "off",
      "react-hooks/exhaustive-deps": "off",
      "eslint/no-shadow": "off",
      "eslint/no-await-in-loop": "off",
      "eslint/no-underscore-dangle": "off",
      "typescript/consistent-return": "off",
      "typescript/no-base-to-string": "off",
      "typescript/no-duplicate-type-constituents": "off",
      "typescript/no-floating-promises": "off",
      "typescript/no-implied-eval": "off",
      "typescript/no-meaningless-void-operator": "off",
      "typescript/no-redundant-type-constituents": "off",
      "typescript/no-unnecessary-boolean-literal-compare": "off",
      "typescript/no-unnecessary-type-conversion": "off",
      "typescript/no-unnecessary-type-arguments": "off",
      "typescript/no-unnecessary-type-assertion": "off",
      "typescript/no-unnecessary-type-parameters": "off",
      "typescript/no-unsafe-type-assertion": "off",
      "typescript/await-thenable": "off",
      "typescript/require-array-sort-compare": "off",
      "typescript/restrict-template-expressions": "off",
      "typescript/unbound-method": "off",
      "salchi/no-inline-schema-compile": "warn",
    },
    overrides: [
      {
        files: [
          "apps/desktop/src/**/*.ts",
          "apps/desktop/vite.config.ts",
          "apps/server/integration/**/*.ts",
          "apps/server/scripts/**/*.ts",
          "apps/server/src/**/*.ts",
          "apps/server/vite.config.ts",
          "apps/web/src/**/*.ts",
          "apps/web/src/**/*.tsx",
          "apps/web/test/**/*.ts",
          "apps/web/vercel.ts",
          "apps/web/vite.config.ts",
          "oxlint-plugin-salchi/**/*.ts",
          "packages/*/scripts/**/*.ts",
          "packages/*/src/**/*.ts",
          "packages/*/test/**/*.ts",
          "scripts/**/*.ts",
        ],
        rules: {
          ...effectTsgoCorrectness.rules,
          "effecttsgo/any-unknown-in-error-context": "error",
          "effecttsgo/crypto-random-uuid": "error",
          "effecttsgo/crypto-random-uuid-in-effect": "error",
          "effecttsgo/deterministic-keys": "error",
          "effecttsgo/global-console": "error",
          "effecttsgo/global-console-in-effect": "error",
          "effecttsgo/global-date": "error",
          "effecttsgo/global-date-in-effect": "error",
          "effecttsgo/global-error-in-effect-catch": "error",
          "effecttsgo/global-error-in-effect-failure": "error",
          "effecttsgo/global-fetch": "error",
          "effecttsgo/global-fetch-in-effect": "error",
          "effecttsgo/global-random": "error",
          "effecttsgo/global-random-in-effect": "error",
          "effecttsgo/global-timers": "error",
          "effecttsgo/global-timers-in-effect": "error",
          "effecttsgo/instance-of-schema": "error",
          "effecttsgo/lazy-effect": "off",
          "effecttsgo/leaking-requirements": "error",
          "effecttsgo/missing-effect-service-dependency": "error",
          "effecttsgo/node-builtin-import": "error",
          "effecttsgo/prefer-schema-over-json": "error",
          "effecttsgo/schema-sync-in-effect": "error",
          "effecttsgo/strict-boolean-expressions": "off",
          "effecttsgo/strict-effect-provide": "off",
          "effecttsgo/unknown-in-effect-catch": "error",
          "effecttsgo/unsafe-effect-type-assertion": "error",
        },
      },
      {
        files: ["apps/web/**/*.ts", "apps/web/**/*.tsx"],
        rules: {
          "effecttsgo/global-console": "off",
          "effecttsgo/global-date": "off",
          "effecttsgo/global-fetch": "off",
          "effecttsgo/global-random": "off",
          "effecttsgo/global-timers": "off",
        },
      },
    ],
    options: {
      typeAware: true,
      typeCheck: false,
    },
  },
});
